### ISSUE TITLE
1.0 release plan

### ISSUE THREAD

**Issue by mmastrac** [mmastrac/linktime#160]
This is a tracking bug to cover everything we need to do for a 1.0 release:

- [x] #327: doc updates
- [x] #351: Tags for release versions
- [x] #375: Merge proc-macro crates
- [x] #394: Priority tweaks
- [x] #159: make ctor/dtor unsafe, always
- [x] #161: Construction of globals punted to a 3rd-party library
- [x] #124: Remove the dep on `syn`
- [x] #321: Allow `ctor` to specify custom link section

This should be enough to call the library "done", modulo some extra platform support.
